---
- hosts: loadbalancer
  become: true
  gather_facts: false
  tasks:
    - service: name=nginx state=stopped
    - wait_for: port=80 state=drained

- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - service: name=httpd state=stopped
    - wait_for: port=80 state=stopped

- hosts: database
  become: true
  tasks:
    - service: name=mariadb state=restarted
    - wait_for: host={{ ansible_ens18.ipv4.address }} port=3306 state=started

- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - service: name=httpd state=started
    - wait_for: port=80

- hosts: loadbalancer
  become: true
  gather_facts: false
  tasks:
    - service: name=nginx state=started
    - wait_for: port=80
