---
- hosts: database
  become: true
  tasks:
    - name: install tools
      yum: name={{item}} state=present
      with_items:
        - MySQL-python 

    - name: update centos
      yum: 
        name: "*"
        state: latest

    - name: install libselinux
      yum:
        name: libselinux-python
        state: present

    - name: download mysql server repository
      get_url:
        url: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
        dest: /tmp 
        mode: 0440

    - name: install mysql server repository
      yum:
        name: /tmp/mysql-community-release-el7-5.noarch.rpm
        state: present        

    - name: install mysql-server
      yum:
        name: mysql-server
        state: present

    - name: ensure mysql started
      service: name=mysql state=started enabled=yes
        
    - name: ensure mysql listening on all ports
      lineinfile: dest=/etc/my.cnf regexp=^bind-address
                  line="bind-address = 0.0.0.0"
      notify: restart mysql

    - name: create demo database
      mysql_db: name=demo state=present

 #   - name: upgrade mysql tables
 #     command: mysql_upgrade
 #     when: mysql.changed

    - name: create demo user
      mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted

