---
- name: update centos
  yum: name="*" state=latest

- name: install epel
  yum: name=epel-release state=present

- name: install web components
  yum: name={{item}} state=present 
  with_items:
    - httpd
    - mod_wsgi

- name: enale httpd to connect to mysql
  command: setsebool -P httpd_can_network_connect=1

- name: ensure mod_wsgi enabled
  apache2_module: state=present name=wsgi
  notify: restart httpd

- name: ensure http started
  service: name=httpd state=started enabled=yes
