---
- name: install tools
  yum: name={{item}} state=present
  with_items:
    - python-httplib2
  
- name: install epel repository
  yum: 
    name: epel-release
    state: latest

- name: install libselinux
  yum:
    name: libselinux-python
    state: present

- name: install nginx
  yum:
    name: nginx
    state: present

- name: copy nginx default config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf mode=0644
  notify: restart nginx

- name: configure nginx site
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/{{ item.key }} mode=0644
  with_dict: "{{ sites }}"
  notify: restart nginx

- name: get active sites
  shell: ls -1 /etc/nginx/conf.d
  register: active_sites
  changed_when: active_sites.stdout_lines != sites.keys()

- debug:
    msg: "Sites keys: {{ sites.keys() }} vs {{ active_sites.stdout_lines }}"

- name: deactivate sites
  file: 
    path: /etc/nginx/conf.d/{{ item }}
    state: absent
  with_items: "{{active_sites.stdout_lines}}"
  when: item not in sites
  notify: restart nginx

- name: ensure nginx started
  service: name=nginx state=started enabled=yes

