---
- name: install tools
  yum: name={{item}} state=present
  with_items:
    - python-httplib2
  
- name: install epel repository
  yum: 
    name: epel-release
    state: latest

- name: install libselinux
  yum:
    name: libselinux-python
    state: present

- name: install nginx
  yum:
    name: nginx
    state: present

- name: copy nginx default config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf mode=0755
  notify: restart nginx

- name: configure nginx site
  template: src=nginx.conf.j2 dest=/etc/nginx/demo.conf mode=0644
  notify: restart nginx

- name: activate defaults nginx site
  file: src=/etc/nginx/demo.conf dest=/etc/nginx/conf.d/demo.conf state=link
  notify: restart nginx

- name: ensure nginx started
  service: name=nginx state=started enabled=yes

